# https://play.whizlabs.com/site/task_details?lab_type=1&task_id=9&quest_id=35
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: whizlabs1234567
      PublicAccessBlockConfiguration:
        BlockPublicAcls: FALSE
        BlockPublicPolicy: FALSE
        IgnorePublicAcls: FALSE
        RestrictPublicBuckets: FALSE
  MyPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:ListBucket
            Effect: Allow
            Resource: !Ref MyBucket
            Principal: 
              AWS: '*'
          - Effect: Allow
            Action:
              - s3:GetObject
                s3:PutObject
            Principal:
              AWS: '*'
            Resource: !Ref MyBucket
  MyDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: 3417940912
          ViewerProtocolPolicy: allow-all
        Enabled: TRUE
        Origins:
          - DomainName: !GetAtt MyBucket.DomainName
            Id: 3417940912
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/3417940912
        CustomErrorResponses:
          - ErrorCachingMinTTL: 10
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /CustomErrors/error.html
          - ErrorCachingMinTTL: 10
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /CustomErrors/block.html
        Restrictions:
          GeoRestriction:
            Locations:
              - US
            RestrictionType: blacklist

  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-087c17d1fe0178315
      InstanceType: t2.micro
      IamInstanceProfile: !Ref MyIP
      SecurityGroupIds:
        - !GetAtt MySG.GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo su
          curl -o image.jpg https://whizlabsresources.s3.amazonaws.com/task_id_20_whizlabs_logo.png
          aws s3 mv image.jpg s3://whizlabs1234567
          echo "<html><h1>This is Error Page</h1></html>" >> error.html
          aws s3 cp ./errors.html s3://whizlabs1234567/CustomErrors
          echo "<html><h1>This content is blocked in your location!!!</h1></html>" >> block.html
          aws s3 cp ./block.html s3://whizlabs1234567/CustomErrors
          ID=wget -q -O - http://169.254.169.254/latest/meta-data/instance-id
          aws ec2 terminate-instances --instance-ids $ID
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MySG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyIP:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyRole
  
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/S3FullAccess