# https://play.whizlabs.com/site/task_details?lab_type=1&task_id=12&quest_id=35
Resources:
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: RDS_lab_sg
      GroupDescription: Security group for RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 3306
          FromPort: 3306
          CidrIp: 0.0.0.0/0
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceIdentifier: mydatabaseinstance
      MasterUsername: mydatabaseuser
      MasterUserPassword: mydatabasepassword
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      AllocatedStorage: 20
      PubliclyAccessible: TRUE
      VPCSecurityGroups: 
        - !Ref MySG
      DBName: mydatabase
      

