# https://play.whizlabs.com/site/task_details?lab_type=1&task_id=13&quest_id=35

Resources:
  MyDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mydynamodbtable
      AttributeDefinitions:
        - AttributeName: companyid
          AttributeType: N
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: companyid
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE

# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/getting-started-step-2.html 
# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.CLI.html
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-087c17d1fe0178315
      InstanceType: t2.micro
      IamInstanceProfile: !Ref MyIP
      SecurityGroupIds:
        - !GetAtt MySG.GroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
          aws dynamodb put-item \
            --table-name mydynamodbtable \
            --item \
              '{"companyname": "1", "name": "John"}'
          #aws dynamodb query \
          #  --table-name mydynamodbtable \
          #  --index-name name \


  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MySG
      GroupDescription: MySG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyIP:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyRole
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess