# https://play.whizlabs.com/site/task_details?lab_type=1&task_id=21&quest_id=35
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: whizlabs2346
      PublicAccessBlockConfiguration:
        BlockPublicAcls: FALSE
        BlockPublicPolicy: FALSE
        IgnorePublicAcls: FALSE
        RestrictPublicBuckets: FALSE
      VersioningConfiguration:
        Status: Enabled
  MyPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Ref MyBucket
            Principal: '*'
