# https://play.whizlabs.com/site/task_details?lab_type=1&task_id=164&quest_id=35
Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref MyTemp
        Version: 1


  MyTemp:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: Spot
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-087c17d1fe0178315
        SecurityGroupIds:
          - !GetAtt MySG.GroupId
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            MaxPrice: .003
            SpotInstanceType: one-time
            # ValidUntil: Nofuckingclue
        UserData:
          Fn::Base64: |
            #!/bin/bash
            sudo su
            yum update -y
            yum install httpd -y
            echo "<html><h1> Welcome to Whizlabs Server</h1><html>" >> /var/www/html/index.html
            systemctl start httpd
            systemctl enable httpd
        TagSpecifications:
          - ResourceType: instance
            Tags:
            - Key: Name
              Value: MySpotInstance

  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MyEC2SecurityGroup
      GroupName: MyEC2SecurityGroup
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0